version: "3.9"


services:

  backend:
    build:
      dockerfile: ./Dockerfile
      target: development
    networks:
      - my-network
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env.development
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3000"
    command: npm run start:development
    

networks:

  my-network:
    driver: bridge